neutree-ai/neutree

- .github/workflows/release.yaml
release ci build arm64 image failed due to use amd64 arch basic env
Package amd64 and arm64 images separately, then merge and push manifests
> fix: release ci failed build arm64 image

- .github/workflows/daily-build.yaml
daily build workflow will not trigger release workflow, see the reason for https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
1. use `github-script` to trigger release workflow.
2. add manual trigger for daily build 
fork repo test
> fix: daily build can not trigger release workflow

- .golangci.yaml
- api/v1/api_gen.go
- api/v1/api_key_types.go
- api/v1/endpoint_types.go
- api/v1/engine_types.go
- cluster-image-builder/requirements.txt
- cluster-image-builder/serve/llama_cpp/v1/app.py
- cmd/neutree-core/neutree-core.go
- controllers/api_key_controller.go
- controllers/cluster_controller.go
- controllers/cluster_controller_test.go
- controllers/endpoint_controller.go
- controllers/endpoint_controller_test.go
- controllers/engine_controller.go
- db/migrations/003_resources.up.sql
- internal/orchestrator/mocks/mock_orchestrator.go
- internal/orchestrator/orchestrator.go
- internal/orchestrator/orchestrator_test.go
- internal/orchestrator/ray/command_runner/docker_command_runner.go
- internal/orchestrator/ray/dashboard/client.go
- internal/orchestrator/ray/dashboard/mocks/mock_dashboard_service.go
- internal/orchestrator/ray/dashboard/serve.go
- internal/orchestrator/ray_orchestrator.go
- internal/orchestrator/ray_orchestrator_test.go
- pkg/storage/mocks/mock_storage.go
- pkg/storage/postgrest.go
- pkg/storage/storage.go
There are several architectural changes in this patch. @Levi080513, please check whether these are the decent ways.
1. The `getRelateImageRegistry` function has been moved into the orchestrator constructor, so the controllers can share this function.
2. The `RayOrchestrator` now has a `RayOptions` param,  which equals to`Options` + `ImageRegistry`.
3. Now the orchestrator can access storage/api.
4. Since we need to call the Ray dashboard's serve APIs, I've extended the Ray dashboard client. Instead of adding new functions into `client.go`, I've created a separate `serve.go` file to include the serve API clients.
WIP: still need E2E tests to check this patch.
> impl the endpoint controller

- api/v1/basic_types.go
- cluster-image-builder/Dockerfile
- cmd/neutree-cli/app/cmd/launch/core.go
- cmd/neutree-cli/app/cmd/launch/launch.go
- cmd/neutree-cli/app/cmd/launch/obs_stack.go
- controllers/cluster_controller.go
- controllers/cluster_controller_test.go
- controllers/image_registry_controller.go
- controllers/model_registry_controller.go
- controllers/workspace_controller.go
- controllers/workspace_controller_test.go
- internal/orchestrator/ray/cluster/kubernetes.go
- internal/orchestrator/ray/cluster/ssh.go
- internal/orchestrator/ray/cluster/ssh_test.go
- internal/orchestrator/ray_orchestrator.go
- pkg/model_registry/hugging_face.go
feat: auto create workspace engines
feat: auto init workspace engines
others changes
1.  fix cluster delete hang due to unexpected cluster config
2. add neutree-cli launch --dry-run options
3. fix list model failed
4. fix cpu pod detected gpu devices
5. only set registry CA when cluster ssh_user is root
6. add `--num-cpus=0` params when start head node on kubernetes
7. Downgrade cluster image cuda version
auto create workspace engines
common k8s cluster test
> feat: auto create workspace engines

- deploy/chart/neutree/templates/migration-job.yaml
- deploy/chart/neutree/templates/post-migration-hook-job.yaml
- deploy/chart/neutree/templates/postgresql-deployment.yaml
postgresql data always re-init when pod recreate due to the image mount /var/lib/postgresql/data
use volume subpath mount /var/lib/postgresql/data
other changes
1. migration/post-migration-hook job adds postgresql health wait
recreate pod, the log show `Skipping initialization`
> fix: postgresql data always re-init when pod recreate

- db/migrations/004_required_fields.down.sql
- db/migrations/004_required_fields.up.sql
Previously, we did not validate resource metadata, so users could create invalid resources.
Add DB validations(function + trigger), so every client(API/UI) can be validate correctly.
We also customize the error code, so Postgrest will return the error code in the response body, and the UI can do i18n via the error code.
Creating a resource without name and workspace
```
node examples/simple.js
{
error: {
code: '10001',
details: null,
hint: 'Please provide a valid name in the metadata object',
message: 'metadata.name is required for the resource'
},
data: null,
count: null,
status: 400,
statusText: 'Bad Request'
}
```
```
node examples/simple.js
{
error: {
code: '10002',
details: null,
hint: 'Please provide a valid workspace in the metadata object',
message: 'metadata.workspace is required …
```
> feat: add validations to resource metadata

- cluster-image-builder/requirements.txt
> chore: bump cluster-image kantoku to 0.18.3

- Makefile
> chore: bump default cluster image version to v19

- deploy/chart/neutree/templates/neutree-api-service.yaml
- deploy/chart/neutree/values.yaml
Unable to specify a custom NodePort port
1. Support custom NodePort for NeuTree API Service.
2. Improved the values.yaml file by removing unnecessary whitespace.
> Support custom NodePort for NeuTree API Service.

- cmd/neutree-api/neutree-api.go
- cmd/neutree-cli/app/cmd/launch/core.go
- deploy/chart/neutree/templates/neutree-api-deployment.yaml
- deploy/chart/neutree/values.yaml
- deploy/docker/neutree-core/docker-compose.yml
- internal/routes/system/system.go
- internal/routes/system/system_test.go
The UI needs to load Grafana panels, which requires either proxying requests through the server or accessing Grafana directly via its URL.
After exploring several approaches outlined in [Grafana’s reverse proxy guide](https://grafana.com/tutorials/run-grafana-behind-a-proxy/), we were unable to find a reliable way to proxy all Grafana panel requests under a subpath of our server.
As a workaround, we now expose a system API that returns the Grafana URL configured by the user during deployment. The UI can then use this URL to communicate with Grafana directly.
Manually tested in the UI.
> return grafana URL in system API

- cluster-image-builder/requirements.txt
The latest vLLM could not work with old GPUs like T4, so we downgraded it before they fix it.
https://github.com/vllm-project/vllm/issues/19203
> fix: downgrade vllm to fit Tesla T4

- internal/orchestrator/ray/dashboard/serve.go
fix: download HF gated models failed
config `HF_TOKEN/HF_ENDPOINT` Env to ray application 
config credentials to download `google/gemma-3-4b-it `
> fix: download HF gated models failed

- api/v1/cluster_types.go
- api/v1/model_registry_types.go
- internal/orchestrator/ray/cluster/kubernetes.go
- internal/orchestrator/ray/cluster/manager.go
- internal/orchestrator/ray/cluster/ssh.go
- internal/orchestrator/ray/cluster/ssh_test.go
- internal/orchestrator/ray/dashboard/serve.go
- pkg/model_registry/bentoml/bentoml.go
Supports configuring multiple different types of model registry cache configurations, e.g. hugging-face, bentoml etc.
- For SSH cluster type, we can configure model cache, and the models downloaded from HF hub or BentoML cloud will be downloaded to hostPath.
- For Kubernetes cluster type, we can configure model cache, and the models downloaded from HF hub or BentoML cloud will be downloaded to hostPath or NFS.
create ssh cluster which use hostPath `/home/hf` cache HF model
```
{ "api_version": "v1", "kind": "Cluster", "metadata": { "name": "gpu", "workspace": "default" }, "spec": { "type": "ssh", "config": { "provider": { "head_ip": "10.255.1.84" }, "auth": { "ssh_user": "root", "ssh_private_key": "" }, "model_caches": [{"host_path": …
```
> feat: support model cache

- api/v1/api_gen.go
- db/migrations/008_oem_config.down.sql
- db/migrations/008_oem_config.up.sql
- db/migrations/009_oem_config.down.sql
- db/migrations/009_oem_config.up.sql
The OEM feature is simple in the backend; we are just adding a new resource `oem_configs`, and letting the client side customize the config and display the content in the UI.
Also, we can re-use the export/import features in the client to port an OEM config from one neutree to another neutree.
We also add a new permission action `system:admin` to control the RLS of this resource, which only lets the admin user customize the OEM config by default.
We are using a unique index to ensure that only one OEM configuration exists.
Posted a test video in our internal channel.
> feat: OEM config

- api/v1/model_registry_types.go
- internal/orchestrator/ray/dashboard/serve.go
remove `HF_TOKEN` env when huggingface model registry credentials is empty string
credentials is not empty string
credentials is empty string
> fix: vllm download model failed due to HF token is empty string

- db/migrations/010_oem_config_read_policy.down.sql
- db/migrations/010_oem_config_read_policy.up.sql
The login page(not authenticated yet) also needs to fetch the OEM config and display the logo and brand name.
> fix: login page also need OEM config

- .golangci.yaml
- cmd/neutree-cli/app/cmd/model/push.go
- go.mod
- go.sum
- internal/routes/models/models.go
- pkg/client/model.go
- pkg/model_registry/bentoml/bentoml.go
- pkg/model_registry/file_based.go
- pkg/model_registry/hugging_face.go
- pkg/model_registry/mocks/mock_model_registry.go
- pkg/model_registry/model_registry.go
Previously, we used the `bentoml` Python CLI to manage the models on the server side and implement our own APIs and client/CLI on top of it.
However, the UX suffered because there are no indicators about the lengthy task, and the task's speed is also slow.
We've built multiple improvements to the model management UX in this patch:
1. Add progress bars to the model push command, including archiving, uploading, and server-side importing.
2. Optimize the speed of the push command.
- Use a larger buffer(16mb) for the copy process.
- Use the pgzip lib to do parallel gzip, which is good for large model files.
- Implement the alternative to `bentoml model import` in Go, which removes the slow Python implementation.
- Remove some duplicate IO paths.
3. Since the model list command is also used …
> feat: optimize model management

- internal/accelerator/plugin/gpu.go
- internal/accelerator/plugin/gpu_test.go
set `"NVIDIA_VISIBLE_DEVICES": "void"` Env on no gpu request container 
the head node pod which request no gpu resource never has gpu resource even if scheduled to the GPU k8s node.
> fix: ray head pod request no gpu resource but mount all node gpu device

- pkg/model_registry/bentoml/bentoml.go
bentoml converts model names and model versions to lowercase, we should keep the behavior consistent
import model
model list
> fix:  model import and list query behavior is inconsistent with bentoml

- internal/accelerator/manager.go
- internal/accelerator/manager_test.go
cpu cluster use default cuda base image, when pod schedule to gpu node, nvidia-container-runtime will mount all gpu to container even has no gpu request.
kubernetes cpu cluster add `NVIDIA_VISIBLE_DEVICES=void` env.
all ray pod schedule to gpu node
ray cluster detect zero gpu
> fix: Kubernetes cpu cluster mount all gpu device on node to container

- db/migrations/012_self_contained_api_key.down.sql
- db/migrations/012_self_contained_api_key.up.sql
- deploy/chart/neutree/templates/postgrest-deployment.yaml
- deploy/docker/neutree-core/docker-compose.yml
- internal/middleware/auth.go
- internal/middleware/auth_test.go
- internal/routes/models/models.go
- internal/routes/proxies/proxies.go
- internal/routes/system/system.go
Improves API key authentication performance by implementing self-contained API keys that eliminate database queries during authentication, similar to JWT tokens.
- Database Changes:
- Added expires_in field to api_key_spec type
- Implemented compact binary encoding for API keys: user_id (16 bytes) + key_id (16 bytes) + expires_at (8
bytes)
- Updated generate_api_key() function to use AES-256 encryption with PostgreSQL's encrypt() function
- Added HMAC signature verification (truncated to 16 bytes for compactness)
- Updated create_api_key() function to support optional expiration time
- Go Authentication Middleware:
- Implemented parseSelfContainedAPIKey() function with AES-256/CBC decryption
- Added proper key length handling to match PostgreSQL's AES variant selection (AES-128/192/256)
- …
> feat: introduce self-contained API key

- internal/gateway/kong.go
- internal/orchestrator/ray/dashboard/serve.go
- internal/routes/proxies/proxies.go
- internal/routes/proxies/proxies_test.go
The serve URL and proxy URL do not have workspace info in them, and may have conflicts across workspaces.
1. Add workspace to serve's app name and prefix URL
> chore: add workspace info to URL path

- db/migrations/016_role_assignments.down.sql
- db/migrations/016_role_assignments.up.sql
| Field               | Error Code | Validation Logic                                                             |
|--------------------|------------|------------------------------------------------------------------------------|
| `spec.user_id`     | 10032      | Must not be null                                                             |
| `spec.role`        | 10033      | Must not be null or empty                                                    |
| `spec.workspace`   | 10034      | Must not be null or empty **when** `spec.global` is `true`                   |
---
- If any of the above validations fail:
- A specific **error code** is returned (10032–10034)
- The request is rejected with HTTP **400 Bad Request**
- The error includes a detailed message and a helpful hint
> Add Validation for `role_assignment_spec` Composite Type

- cmd/neutree-cli/app/cmd/model/push.go
- internal/orchestrator/ray_orchestrator_test.go
- internal/routes/models/models.go
- pkg/model_registry/bentoml/bentoml.go
1. limit upload latest version model
2. recreate latest tag when model upload success
3. fix the abnormal permissions of the model version directory file
The test model was uploaded and the inference was successful using the model.
> fix: limit upload latest version model
