- api/v1/basic_types.go
- cmd/main.go
- controllers/image_registry_controller.go
- db/init-scripts/v1.sql
- docker-compose.yml
- pkg/storage/storage.go
https://github.com/neutree-ai/prototype/issues/1
1. Add creation_timestamp, update_timestamp column to metadata type
2. Improve code structure
3. docker-compose adds the startup of pg related components
image_registry 
model_registry
engines
clusters
endpoints
> feat: Add creation_timestamp, update_timestamp column to metadata type

- .dewhale/characters/OpsPilot.yaml
- .dewhale/config.yaml
- .github/workflows/dewhale-issue-trigger.yaml
introduce dewhale characters to help us.
> chore: integrate dewhale characters

- controllers/base_controller.go
- controllers/cluster_controller.go
- controllers/image_registry_controller.go
- controllers/model_registry_controller.go
Extract base controller logic to simplify controller development
1. extract base controller logic
model registry reconcile
image registry reconcile
cluster reconcile
> refactor: extract base controller logic

- .dewhale/characters/OpsPilot.yaml
- .github/workflows/daily-build.yaml
- .github/workflows/release.yaml
> chore: add manual trigger release workflow

- cmd/main.go
- docker-compose.yml
> chore: start newly added controllers

- api/v1/api_gen.go
- api/v1/engine_types.go
- controllers/engine_controller.go
- controllers/engine_controller_test.go
- db/migrations/003_resources.up.sql
- docker-compose.yml
- pkg/storage/mocks/mock_storage.go
- pkg/storage/postgrest.go
- pkg/storage/storage.go
1. Update the schemas of the engine and the endpoint
2. Implement the engine controller
> first patch of engine and endpoint

- cluster-image-builder/Dockerfile
- cluster-image-builder/serve/_replica_scheduler/chwbl_scheduler.py
- cluster-image-builder/serve/_replica_scheduler/static_hash_scheduler.py
- cluster-image-builder/serve/llama_cpp/v1/app.py
- cluster-image-builder/serve/vllm/v1/app.py
- cluster-image-builder/start.py
Now both the vllm and llama-cpp implementations have:
- The app builder pattern to get args from the control plane
- The controller-backend pattern, where the controller sets the replica scheduler
- The llama-cpp engine supports embedding, and the old llama-cpp-embedding engine is no longer need
The unit/e2e tests of engines need to be designed.
> feat: migrate serve impl to core repo

- db/seed/001_default-role-and-users.sql
> fix: update default role to the new naming format

- deploy/docker/neutree-core/docker-compose.yml
kong container env `KONG_PG_DB` => `KONG_PG_DATABASE `
> fix: kong container always failed when installed by cli launch

- internal/orchestrator/ray/cluster/kubernetes.go
- internal/orchestrator/ray/cluster/ssh.go
- internal/orchestrator/ray/cluster/ssh_test.go
fix: delete endpoint/cluster hang due to cluster image not exist
Adjust the timing of checking images to only check when creating a cluster, synchronizing a cluster, and adding nodes.
By modifying the image repository configuration to simulate the scenario of cluster image loss, the test passed.
> fix: delete endpoint/cluster hang due to cluster image not exist

- api/v1/engine_types.go
- cluster-image-builder/serve/vllm/v1/app.py
- controllers/workspace_controller.go
Support rerank and embedding type inference tasks in the vLLM engine.
Since we are using the vLLM engine of 0.7.2, which does not have built-in rerank support, we implement the rerank on top of the general score API by ourselves. In the implementation, we align the schema and business logic with the latest vLLM, so when we upgrade vLLM, the feature should not have any difference.
Using the following ray serve config to start the endpoint:
```yaml
proxy_location: EveryNode
http_options:
host: 0.0.0.0
port: 8000
grpc_options:
port: 9001
grpc_servicer_functions: []
logging_config:
encoding: TEXT
log_level: INFO
logs_dir: null
enable_access_log: true
applications:
- name: app
route_prefix: /vllm
import_path: serve.vllm.v1.app:app_builder
args:
model:
registry_type: "hugging-face"
name: …
```
> feat: Rerank and Embedding in vllm

- cmd/neutree-cli/app/cmd/launch/core.go
- cmd/neutree-core/neutree-core.go
- controllers/cluster_controller.go
- controllers/cluster_controller_test.go
- controllers/endpoint_controller.go
- controllers/endpoint_controller_test.go
- controllers/workspace_controller.go
- deploy/chart/neutree/templates/kong-install.yaml
- deploy/chart/neutree/templates/kong-plugin-neutree-ai-statistics.yaml
- deploy/chart/neutree/templates/neutree-core-deployment.yaml
- deploy/chart/neutree/templates/neutree-rbac.yaml
- deploy/chart/neutree/templates/vector-install.yaml
- deploy/chart/neutree/values.yaml
- deploy/docker/neutree-core/docker-compose.yml
- deploy/docker/neutree-core/kong/plugin/kong/plugins/neutree-ai-statistics/handler.lua
- deploy/docker/neutree-core/kong/plugin/kong/plugins/neutree-ai-statistics/schema.lua
- deploy/docker/neutree-core/vector/vector.yml
- gateway/kong/plugin/neutree-ai-statistics/handler.lua
- gateway/kong/plugin/neutree-ai-statistics/schema.lua
- internal/gateway/gateway.go
- internal/gateway/kong.go
- internal/gateway/mocks/mock_gateway.go
- internal/orchestrator/ray_orchestrator.go
- internal/routes/proxies/proxies.go
- internal/routes/proxies/proxies_test.go
add Kong AI statistics plugin
1. add Kong AI statistics plugin and integrated deployment
2. endpoint route uses ai statistics plugin instead of ai proxy plugin
3. support proxy all endpoint api path
4. use gateway proxy url as endpoint serviceUrl
other changes
1. add workspace and endpoint info in api_usage_records model field
use gateway proxy url as endpoint serviceUrl
model list test
```
curl 'http://10.255.1.54:80/workspace/default/endpoint/qwen25-0p5b-chat-cpu/v1/models' \
-H 'Content-Type: application/json' \
-H 'Authorization: Bearer sk_2533217ac9c9e999a128a41b5fdfb2f34f8f92ad7309e7d9'
{"object":"list","data":[{"id":"Qwen/Qwen2-0.5B-Instruct-GGUF:latest","object":"model","permissions":[],"owned_by":"local"}]
```
test chat
```
curl …
```
> feat: Add Kong AI statistics plugin

- controllers/model_catalog_controller.go
- controllers/model_catalog_controller_test.go
Add delete handler to the model catalog controller
> chore: support delete model catalog in the controller

- cluster-image-builder/serve/llama_cpp/v1/app.py
- cluster-image-builder/serve/vllm/v1/app.py
Now, users can define tool calling and chat-related args by setting the engine args.
> feat: support more useful vllm engine args

- cluster-image-builder/start.py
> improve: add L20 to accelerator markers

- cluster-image-builder/serve/vllm/v1/app.py
1. Let the user customize the chat template in vLLM
2. Pop our own args from the engine_args object, so the AsyncEngineArgs init will not fail
Now the endpoints can use tools
> Let the user customize the chat template in vLLM

- cluster-image-builder/serve/vllm/v1/app.py
Pass reasoning args to the `OpenAIServingChat`.
> feat: support reasoning in vLLM

- cmd/neutree-api/neutree-api.go
- deploy/chart/neutree/templates/neutree-api-deployment.yaml
- deploy/docker/neutree-core/docker-compose.yml
- internal/routes/system/system.go
- internal/routes/system/system_test.go
> feat: add version to system info API

- Makefile
> chore: bump cluster image version to v21

- deploy/chart/neutree/templates/neutree-core-server-service.yaml
> chore: adjust chart neutree core server service name

- internal/orchestrator/ray/cluster/kubernetes.go
> fix: panic due to wrong cluster resource configuration

- .github/workflows/release-serve.yaml
- cluster-image-builder/Dockerfile.rocm
- cluster-image-builder/Dockerfile.rocm_base
- cluster-image-builder/Makefile
- cluster-image-builder/accelerator/amd_gpu.py
- cluster-image-builder/requirements/common.txt
- cluster-image-builder/requirements/cuda.txt
- cluster-image-builder/requirements/cuda_arm.txt
- cluster-image-builder/requirements/rocm.txt
- cluster-image-builder/serve/llama_cpp/v1/app.py
- go.mod
- internal/accelerator/manager_test.go
- internal/accelerator/plugin/amd_gpu.go
- internal/accelerator/plugin/amd_gpu_test.go
- internal/orchestrator/ray/cluster/kubernetes.go
feat: Support AMD GPU
1. Add the ROCM base image build Dockerfile to decrease ROCM image build time
2. Add the ROCM image build Dockerfile to support vllm/llama engine run on ROCM.
3. Add the `amd-gpu` accelerator plugin to support AMD GPU detect and runtime config.
other changes:
1. adjust vmagent image namespace
some limits:
1. amd container runtime only support ubuntu 22.04 or ubuntu 24.04，so we can only run ssh cluster in above os.
2. only build serve image on amd64 arch for amd gpu does not support arm64
ssh cluster, test amd accelerator is AMD MI300X
kubernetes cluster, test amd accelerator is AMD MI300X
> feat: Support AMD GPU

- .github/workflows/daily-build.yaml
- .github/workflows/release.yaml
- Makefile
Now release workflow supports configuration of ui version and default cluster version
other changes:
Automatically update the helm chart version when executing a release
> chore: Optimize the release workflow

- pkg/model_registry/hugging_face.go
- pkg/model_registry/hugging_face_test.go
- pkg/model_registry/model_registry.go
> fix: always use huggingface.co search models

- controllers/cluster_controller.go
- controllers/image_registry_controller.go
- controllers/model_registry_controller.go
- internal/orchestrator/ray/cluster/ssh.go
> fix: resource status is not displayed correctly

- deploy/chart/neutree/templates/kong-install.yaml
- deploy/docker/neutree-core/docker-compose.yml
adjust kong client_body_buffer_size => 20m
`maxKB` test passed
> fix: kong plugin get raw body is nil

- cluster-image-builder/serve/llama_cpp/v1/app.py
Test llama cpp engine passed and can load model in advance
> chore: try init LlamaProxy instance when init backend

- deploy/chart/neutree/values.yaml
- deploy/docker/neutree-core/docker-compose.yml
> chore: determine the dependent image version

- internal/accelerator/manager.go
- internal/accelerator/manager_test.go
accelerator plugin tcp conn leak
Test Pass
> Fix: register plugin handle always new httpClient cause tcp conn leak
